spring.application.name=minitrello
spring.datasource.url=jdbc:postgresql://localhost:5432/minitrello
spring.datasource.username=minitrellodb
spring.datasource.password=dbtrello
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.web.resources.add-mappings=false
logging.level.org.springframework.security=DEBUG

auth.secret-key=394a1bb903b975f053b355b20fce6246c52e44c16297c09045862261f303cd2a
auth.access-token-expiration-minutes=10
auth.refresh-token-expiration-days=7
auth.issuer=minitrello
auth.access-cookie-name=access_token
auth.refresh-cookie-name=refresh_token
auth.cookie-secure=false
auth.cookie-same-site=Lax
auth.refresh-cookie-path=/auth