spring.application.name=minitrello
spring.datasource.url=jdbc:postgresql://localhost:5432/minitrello
spring.datasource.username=minitrellodb
spring.datasource.password=dbtrello
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect